name: ishaf_cli
description: custom flutter cli for easy life
version: 0.0.3

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0

executables:
  ipp: ishaf_cli
